### ISSUE TITLE
Command line oneliner:

### ISSUE THREAD

**Issue by mollerhoj** [abhishekkrthakur/sandesh#1]
Hey, I just do:
```
curl -X POST --data "{'text': 'some message' }" https://hooks.slack.com/services/...
```
I use it for all that long running deep learning stuff ;-) etc:

```
python3 train.py | curl -X POST --data "{'text': 'done training' }" https://hooks.slack.com/services/...
```

anyways, just saw this repo and thought I'd share

**Comment by abhishekkrthakur** [comment]
yeah, its simple but we dont want all outputs to be sent to slack do we? also, please dont share your webhook publicly ;)
